### ISSUE TITLE
Can i use this theme for my project

### ISSUE THREAD

**Issue by Dione-stack** [OFFLINE-GmbH/oc-mall-theme#10]
Hello and thank you for creating such useful plugins as Mall and SiteSearch, i know that this theme is just a demo and isn't meant for practical use, but do i have permission to use it anyway, because i don't have any other choice. I can't create such a complicated theme duo to my limited knowledge in web development, and if i can use it, do you recommend it?

**Comment by tobias-kuendig** [comment]
Sure, the theme is MIT licensed, so you can do with it whatever you want! Good luck!
