### ISSUE TITLE
Class name is not registered for the component "wishlists". Check the component plugin.

### ISSUE THREAD

**Issue by bonniss** [OFFLINE-GmbH/oc-mall-theme#4]
I installed the plugin oc-mall. The backend is ok. Then I added the oc-mall-theme. The frontend threw error on "wishlist" as the issue title. I have go around and find that the wishlist is a pretty new feature in the changelog. So guys, any way to fix it?

**Comment by tobias-kuendig** [comment]
You can enable edge updates in October to get the newest version of the plugin.

**Comment by bonniss** [comment]
I have updated to the oc-mall to the latest. Nothing is new.

**Comment by tobias-kuendig** [comment]
1.4.0 is the latest when you enable edge updates. Is that the installed version?

https://octobercms.com/docs/setup/configuration#edge-updates

**Comment by tobias-kuendig** [comment]
The new features are now available via the default update channel. Please report back if you still experience any issues.
