### ISSUE TITLE
Service modal window not showing

### ISSUE THREAD

**Issue by igor-tv** [OFFLINE-GmbH/oc-mall-theme#7]
When adding product to the cart, the service selection window is not displayed. A service has been created for the tested product. I checked on a cleanly installed site only with your plugin and your theme on demo data.

There is no such problem on your live demo site.

**Comment by tobias-kuendig** [comment]
Do you have any JS console errors? Is the `[mallDependencies]` component correctly added to your layout? (https://offline-gmbh.github.io/oc-mall-plugin/getting-started/theme-setup.html#layout line 8)

**Comment by igor-tv** [comment]
After a clean installation of a theme from Marketplace, the default.htm layout does not have the [line](https://github.com/OFFLINE-GmbH/oc-mall-theme/blob/126e702bbabb0e3683a56d68d3150a3d8c733cec/layouts/default.htm#L39) `{% component 'mallDependencies' %}` in the head.
```
description = "Default"

[cart]
showDiscountApplier = 1
showTaxes = 1

[mallDependencies]

[session]
security = "all"

[staticPage]
useContent = 1
default = 0

[currencyPicker]

[localePicker]
forceUrl = 1

[enhancedEcommerceAnalytics]
==
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="description" content="{{ this.page.meta_description }}">
    <title>{{ this.page.title }}</title>
    {% styles %}
    <link rel="stylesheet" href="{{ 'assets/main.css' | theme }}">
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"
            integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
            crossorigin="anonymous"
    ></script>
    {% component 'enhancedEcommerceAnalytics' %}
</head>
<body>
{% partial 'header' %}
{% partial 'navigation' %}

<main class="container mx-auto py-8">
    {% page %}
</main>

{% partial 'footer' %}
<script src="{{ 'assets/app.js' | theme }}"></script>
{% framework extras %}
{% scripts %}

{% flash %}
    <script>
        $(function() {
            $.oc.flashMsg({type: '{{ type }}', text: '{{ message }}'})
        })
    </script>
{% endflash %}
</body>
</html>
```

**Comment by igor-tv** [comment]
But even after adding mallDependencies the problems do not go away. It seems that there are no necessary styles to correctly display the modal window. 
<img width="1437" alt="bad modal" src="https://user-images.githubusercontent.com/6777469/68227201-58ecbb00-0004-11ea-9ad3-1812d71acdd5.png">

And the ratings are not displayed as they should.
<img width="929" alt="bad ratings" src="https://user-images.githubusercontent.com/6777469/68227362-99e4cf80-0004-11ea-9c73-ea259bd83700.png">

**Comment by tobias-kuendig** [comment]
Thank you for this report. The theme on the marketplace was not up to date. Can you try with the latest version?

**Comment by igor-tv** [comment]
Now everything is all right, thanks!
